language: c
#cache: ccache

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov
            - valgrind

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: clang
      env: T=normal
    - os: linux
      dist: trusty
      compiler: gcc
      env: T=normal
    - os: linux
      dist: precise
      compiler: clang
      env: T=normal
    - os: linux
      dist: precise
      compiler: gcc
      env: T=normal
    - os: osx
      compiler: clang
      env: T=normal
    - os: linux
      compiler: gcc
      dist: precise
      env: T=coverage
    - os: linux
      compiler: gcc
      dist: precise
      env: T=full-valgrind-checks
    - os: linux
      compiler: gcc
      dist: precise
      env: T=ctgrind
  allow_failures:
    - os: osx
      compiler: clang
      env: T=normal
    - os: linux
      compiler: gcc
      dist: precise
      env: T=ctgrind

sudo: required

before_install:
# Update the repo
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update --quiet --assume-yes; fi

# Dependencies
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install splint && brew install valgrind && brew install curl && brew install glib; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install splint --quiet --assume-yes; fi
- if [[ "$T" = "coverage" ]]; then sudo apt-get install splint --quiet --assume-yes; fi

before_script:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install libgcrypt && brew install libsodium; fi
  - mkdir .deps
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then curl https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.26.tar.bz2 | tar xjf - -C .deps; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then pushd .deps/libgpg-error-1.26 && ./configure && make && sudo make install && popd; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then curl https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.1.tar.bz2 | tar xjf - -C .deps; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then pushd .deps/libgcrypt-1.8.1 && ./configure && make && sudo make install && popd; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then git clone --depth=1 https://github.com/jedisct1/libsodium.git .deps/libsodium; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then pushd .deps/libsodium && ./autogen.sh && ./configure && make && sudo make install && popd; fi
  - if [[ $T == 'ctgrind' ]]; then git clone --depth=1 https://github.com/jedisct1/ctgrind .deps/ctgrind; fi
  - if [[ $T == 'ctgrind' ]]; then pushd .deps/ctgrind && ./autogen.sh && ./configure && make && sudo make install && popd; fi
  - git clone --depth=1 https://bugs.otr.im/lib/libotr.git .deps/libotr
  - pushd .deps/libotr && ./bootstrap && ./configure && make && sudo make install && popd
  - git clone --depth=1 https://github.com/twstrike/ed448goldilocks .deps/goldilocks
  - pushd .deps/goldilocks && ./autogen.sh && ./configure && make && sudo make install && popd

script:
  - export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}
  - export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:${PKG_CONFIG_PATH}"
  - |
      if [ "$T" = "coverage" ]; then
           ./autogen.sh
           ./configure --disable-shared --enable-code-coverage
           make ci
           make coverage-check
      fi
  - |
      if [ "$T" = "full-valgrind-checks" ]; then
           ./autogen.sh
           ./configure --enable-valgrind
           make check-valgrind
      fi
  - |
      if [ "$T" = "normal" ]; then
           ./autogen.sh
           ./configure --disable-shared
           make ci
      fi
  - |
      if [ "$T" = "ctgrind" ]; then
           ./autogen.sh
           ./configure --with-ctgrind
           make ci
      fi
