language: c

sudo: required

before_install:
  - sudo apt-get update --quiet --assume-yes
  - sudo apt-get install splint --quiet --assume-yes
  - sudo apt-get install valgrind --quiet --assume-yes

before_script: 
  - mkdir .deps
  - git clone https://github.com/twstrike/ed448goldilocks-decaf.git .deps/decaf
  - pushd .deps/decaf && ./autogen.sh && ./configure && make && sudo make install && popd
  - curl https://download.libsodium.org/libsodium/releases/libsodium-1.0.11.tar.gz | tar xzf - -C .deps
  - pushd .deps/libsodium-1.0.11 && ./autogen.sh && ./configure && make && sudo make install && popd

script: ./autogen.sh && ./configure && make ci
